projects:
  ChatAPI:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: android
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-east-1
        apiId: 737evs3ivncv7o5zwucqcymwvm
        maxDepth: 2
extensions:
  amplify:
    version: 3
